# Example Podfile for the Prototype framework

target 'Prototype Example iOS' do
  platform :ios, '10.0'

  use_frameworks!
  pod 'Prototype', :path => '../'
end

target 'Prototype Example macOS' do
  platform :osx, '10.12'

  use_frameworks!
  pod 'Prototype', :path => '../'
end

target 'Prototype Example tvOS' do
  platform :tvos, '10.0'

  use_frameworks!
  pod 'Prototype', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.new_shell_script_build_phase.shell_script = "mkdir -p $PODS_CONFIGURATION_BUILD_DIR/#{target.name}"
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end
